### ISSUE TITLE
O(N) lookup

### ISSUE THREAD

**Issue by andreis** [bkaradzic/go-emailvalidator#2]
Not a huge issue, but you seem to do an [O(N) lookup](https://github.com/bkaradzic/go-emailvalidator/blob/master/email.go#L512-L516) for no good reason. Using a `map[string]struct{}{}` would be more efficient, as you don't need to look through the whole array for a match.

Check out: https://github.com/lavab/disposable/blob/master/.generate/generate.go

**Comment by bkaradzic** [comment]
Originally list was pretty short and then I didn't end up using it... Your project looks cool, will switch to use that instead in case I need it! Bonus it removes need to use Python script... :)

**Comment by bkaradzic** [comment]
Added your project here: https://github.com/bkaradzic/go-emailvalidator#see-also

**Comment by andreis** [comment]
Ha, thank you ^_^

It is indeed a completely gratuitous optimisation, don't know why I even suggested it. (the bane of a programming contests background)
